//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCorp.AdventureWorks.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Products")]
        public string SearchPrimaryIndexName {
            get {
                return ((string)(this["SearchPrimaryIndexName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database")]
        public string DocumentDbDatabase {
            get {
                return ((string)(this["DocumentDbDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Collection")]
        public string DocumentDbCollectionSuffix {
            get {
                return ((string)(this["DocumentDbCollectionSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reviews")]
        public string SearchReviewIndexName {
            get {
                return ((string)(this["SearchReviewIndexName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("docdbimages")]
        public string AzureImageBlobContainerName {
            get {
                return ((string)(this["AzureImageBlobContainerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api-version=2014-07-31-Preview")]
        public string SearchApiVersion {
            get {
                return ((string)(this["SearchApiVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=teched2014store;AccountKey=2/QLHue25UK" +
            "97HaL2niF3M4pAVaYpTo/MEPaXqyYKoNH1CIWawXLlcqnAC/MhOmEq81r6mSdvO46W4Bnv83LHA==")]
        public string AzureImageBlobConnectionString {
            get {
                return ((string)(this["AzureImageBlobConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:ldd07q5vqq.database.windows.net,1433;Database=docdbadventureworksdb;Us" +
            "er ID=davidsh@ldd07q5vqq;Password=Password1;Trusted_Connection=False;Encrypt=Tru" +
            "e;Connection Timeout=30;")]
        public string OrderDatabaseConnectionString {
            get {
                return ((string)(this["OrderDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E667C3C9113D5BABE52047B5FCBE9057")]
        public string SearchApiKey {
            get {
                return ((string)(this["SearchApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://teched2014.search.windows.net/indexes")]
        public string SearchServiceUrl {
            get {
                return ((string)(this["SearchServiceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://teched2014.documents.azure.com:443")]
        public string DocumentDbUri {
            get {
                return ((string)(this["DocumentDbUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fGzzwG+f4AzO+oshK82ahUxVPUgiTmzUDYFZORXrzJZE7y1VBr1qJlw93epO9McIpoCabfRfC6AGj/RD6" +
            "fM54Q==")]
        public string DocumentDbAuthKey {
            get {
                return ((string)(this["DocumentDbAuthKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=teched2014store;AccountKey=2/QLHue25UK" +
            "97HaL2niF3M4pAVaYpTo/MEPaXqyYKoNH1CIWawXLlcqnAC/MhOmEq81r6mSdvO46W4Bnv83LHA==")]
        public string AzureTableBlobConnectionString {
            get {
                return ((string)(this["AzureTableBlobConnectionString"]));
            }
        }
    }
}
